apiVersion: v1
kind: Secret
metadata:
  name: lemmy-config
  namespace: lemmy
type: Opaque
stringData: 
  config.hjson: |
      {
        setup: {
          admin_username: "admin"        
          admin_password: "SOMEVERYSECRETPASSWORD"
          site_name: "Lemmy"
        }

        hostname: "example.com"
        bind: "0.0.0.0"
        # Change in service if you need to instead of here
        port: 8536
        tls_enabled: true

        pictrs: {
          url: "http://pictrs-service/"
          api_key: "SOMEVERYSECRETAPIKEY"
        }

        
        database: {
          database: "lemmy"
          user: "lemmy"
          password: "SOMEVERYSECRETDBPASSWORD"
          host: "IPOFYOURDB"
          port: 5432
          pool_size: 5
        }
      }